### ISSUE TITLE
Plans for Layout, Include, and Block?

### ISSUE THREAD

**Issue by thardy** [harttle/shopify-liquid#1]
This looks great.  Any plans for layout, include, and block - http://docs.mixture.io/templates/?

**Comment by harttle** [comment]
It's right. These features you mentioned are essential for template engines. I'm working on it! @thardy

**Comment by harttle** [comment]
Implemented and Closed. See: 3695eb2d6eb346c00fe3a6e14a272c44815f3091 and 8fbbec089fa4e3db4bec47462b1c08dd65c36648

Documents: 

* https://github.com/harttle/shopify-liquid#includes
* https://github.com/harttle/shopify-liquid#layouts
