### ISSUE TITLE
getTemplate

### ISSUE THREAD

**Issue by thardy** [harttle/shopify-liquid#12]
So... I've finally gotten around to actually using the new async template engine, and overriding the getTemplate function on the engine.  How would you recommend overriding the default behavior of changing the path in {% include 'dog' %} from 'dog' to 'c:\dev\myproject\dog.liquid'?

In my case, I'd just like for path to come into getTemplate simply as 'dog' because that's going to be the name in the database.  Should we setup an option or something that can turn that behavior off?

**Comment by harttle** [comment]
Does the `root` option solve your problem? Express will pass the full path to the template engine, and the `root` option is used to find templates.

**Comment by thardy** [comment]
I think I've solved it by simply moving all the pathing logic into getTemplate itself.  That way, any overrides can do whatever they want.  It was very simple.  I'll send you a pull request.

**Comment by thardy** [comment]
A separate question, but still very tied to getTemplate...  I'm trying to return templates with their own models from the database for includes.  For instance, a template with markup {{title}} might have it's own model with a default title.  If the template including that template has a title, it will be used, otherwise the default that comes with the included template should be used.

How do you recommend getting that to work?  It's looking like it needs to happen somewhere in include.js render function - when liquid.handleCache is called.  Somehow, more than just an array of templates needs to come back.  Potentially, any include tags need to also come back with their own models once fetched from getTemplate.  I haven't dug into this much yet, so I was hoping you had an opinion, especially one that worked well with your existing scope management.

**Comment by harttle** [comment]
I guess your model in the database is like this:

```javascript
var user = {
    "name": "alice",
    "model": "user-card.liquid"
}
```

and you want to render the `user-card.liquid` with this model. An intuitive solution may be override the `User.toString()` to return a rendered HTML (by calling `engine.render`), and just eval the model in the template:

```liquid
{{user}}
```

Or register a filter that renders the model and returns HTML:

```liquid
{{ user | render: 'model' }}
```

It's also possible to push scope when rendering templates, by calling `scope.push()`.
