### ISSUE TITLE
`include` tag doesn't respect the paths specified in `view` while using with express

### ISSUE THREAD

**Issue by ianchenyangzhao** [harttle/shopify-liquid#16]
Hello,

I'm trying to setup a local development/preview environment for theme editing. I was able to get it running with every template file under `templates` folder. But for some reason, when using `include` tags. The `paths` specified in `app.set('views', ['./', './templates'])` is not respected by `include` tag.

Here's an example:

```
var Liquid = require('shopify-liquid');
var express = require('express');
var app = express();
var engine = Liquid({
  extname: '.liquid',
  cache: false});

// register liquid engine
app.engine('liquid', engine.express({
  strict_variables: false,         // Default: fasle
  strict_filters: false            // Default: false
}));
app.set('views', ['./', './templates', './snippets', './layout', './locales']);            // specify the views directory
app.set('view engine', 'liquid');       // set to default
```

in my template:

```
 <div class="grid-uniform">

      {% for product in collections.frontpage.products %}

        {% include 'product-grid-item' %}

      {% else %}
</div>
```

the exception I got is:
`Error: ENOENT: no such file or directory, open '/product-grid-item'
   at Error (native)`
seems like its looking for templates under root path?

How can I fix this or get this to work? Thanks!

**Comment by harttle** [comment]
In the current version, `app.views` is resolved by express, and the [`root`][root] option is resolved by liquid's `include` and `layout` tags. Which means:

Setting the `root` option when initializing the `engine` should solve your problem. I'll try to get `app.views` within the engine. If it works, `app.views` for includes will be available in next release.

[root]: https://github.com/harttle/shopify-liquid#render-from-file

**Comment by IanZhao** [comment]
Thanks @harttle . adding `paths` to [root](https://github.com/harttle/shopify-liquid#render-from-file) option did work for me. It'll be nice to have `app.views` for includes, but I don't think it's necessary anymore.

Also, I'm using `shopify-liquid` to setup a local dev environment for myself and my team so we can develop Shopify Theme and test it locally. But a few of native Shopify filters are missing, which a lot of them can only be used on Shopify platform but would be nice to have a different version of them for developing themes locally.

I pulled out a list of those missing/unnecessary filters here at the bottom. If you don't mind, I can fork, add some of those filters to the package and make a pull request.

Thanks!

# missing filter from shopify-liquid
- Array:
	- concat
	- index
- Html
	- img_tag
	- script_tag
	- stylesheet_tag
- Money
	- money
	- money_with_currency
	- money_without_trailing_zeros
	- money_without_currency
- String:
	- camelcase
	- handle/handleize
	- md5
	- sha1
	- sha256
	- hmac_sha1
	- hmac_sha256
	- pluralize
	- truncate_words
	- url_escape
	- url_param_escape
- URL filters:
	- asset_url
	- asset_img_url
	- file_url
	- file_img_url
	- global_asset_url
	- customer_login_link
	- img_url
	- link_to
	- link_to_vendor
	- link_to_type
	- link_to_tag
	- link_to_remove_tag
	- payment_type_img_url
	- product_img_url
	- shopify_asset_url
	- url_for_type
	- url_for_vendor
	- within
- misc filters:
	- time_tag
	- default_errors
	- default_pagination
	- format_address
	- hex_to_rgba
	- highlight
	- highlight_active_tag
	- json
	- weight_with_unit

**Comment by harttle** [comment]
It's great to have more filters. Feel free to make a pull request when you're ready.

Since there're considerable amount of tags in shopify liquid, we can re-organize source files like this:

```
Array filters
HTML filters
Math filters
Money filters
String filters
URL filters
Additional filters
```
