### ISSUE TITLE
The `plus:` filter fails for string input

### ISSUE THREAD

**Issue by ilg-ul** [harttle/shopify-liquid#18]
I encountered a problem with constructs like this:

```
{{ value | plus: 1 }}
```

when the value is a string.

The error was:

```
(node:82019) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 71): RenderError: cb(...).toFixed is not a function
```

For comparison, the equivalent minus filter works properly with the same value:

```
{{ value | minus: 1 }}
```

Checking the implementations, they are very similar:

```
'minus': bindFixed((v, arg) => v - arg),
'plus': bindFixed((v, arg) => v + arg),
```

I think that the problem is the JavaScript `+` operator, that behaves differently if the first operand is a string.

I'm not sure what the semantic of the original Shopify `plus` tag is, but I guess it is a numeric operation.

In this case I suggest you add an explicit conversion to number, to prevent the error.

Perhaps you should also consider cases when the second operand is a string, and must be converted to number.

NB: The same explicit conversion to number might be required to other tags too, first and second operand.

**Comment by harttle** [comment]
fixed at v1.5.4, available on [npm](https://www.npmjs.com/package/shopify-liquid)

**Comment by ilg-ul** [comment]
did you test cases when the second operand is a string?

```
{{ "4" | minus: "1" }}
```

these cases might occur when using variables that have string values.

same for multiplications, modulo, division, etc.

**Comment by harttle** [comment]
It's OK for operators (multiplication, modulo, division, and minus) which are not supported by `String`.

[here](https://github.com/harttle/shopify-liquid/commit/4719544d49c55cf46097c324de6d6f3788c7dd1c#diff-70e8c04eddb73b8a59bbf3855545c06fR136) is the test case for minus.

**Comment by ilg-ul** [comment]
I could not identify a test case for minus with string second operand.
