### ISSUE TITLE
Is liquid 8-bit clean?

### ISSUE THREAD

**Issue by LarryKlugerDS** [harttle/shopify-liquid#24]
I'm trying some binary output with liquid. Is it 8-bit clean?

Thanks,
Larry

**Comment by harttle** [comment]
As far as I know, the output string does not contain non-ASCII characters. Is there anything else do you need?

**Comment by LarryKlugerDS** [comment]
Hi @harttle,

Thank you for your reply. So you mean that if I put non-ascii characters in a template either directly or via a variable interpolation, they'll be stripped at some point?

Thanks,
Larry

**Comment by harttle** [comment]
That's not true. Shopify-liquid is implemented using JavaScript [String][str], which is Unicode by default. I recommend to have a try with [base64][base64] encoding in transportation layer.

[base64]: https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding
[str]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String
