### ISSUE TITLE
Async Tags: Retrieve templates from database

### ISSUE THREAD

**Issue by thardy** [harttle/shopify-liquid#3]
How can I change layouts and includes to pull the templates from a database or other source than the filesystem?  For example, in liquid-node, I overrode the following in order to cause includes to pull their templates from my own service by name in mongodb...

```
CustomFileSystem.prototype.readTemplateFile = function(path) {
        return templateEngine.getTemplate(path)
            .then((templateObject) => {
                if (templateObject && templateObject.template) {
                    return templateObject.template; // return the template string itself
                }
                else {
                    throw new Error(`template '${path}' not found`);
                }
            });

    };

templateEngine.engine.fileSystem = new CustomFileSystem();
```

I'm looking to replace my current implementation of liquid-node in my content management system with shopify-liquid.  Liquid-node doesn't have the layout, include, and block functionality that you do, and I'm just not into coffeescript, so helping out with that project was difficult for me.  I'm sure this is the first of many requests as I dig into your implementation and see if it will fit my needs :)  I'm looking forward to seeing what your template engine can do.  If this does work out, I will probably have some pull requests along the way.

**Comment by harttle** [comment]
As I mentioned in #4 , the key issue is shopify-liquid's [synchronous rendering][sync]. Indeed, it's tricky to provide async functions based on sync ones. As far as I am concerned, there're two kinds of solutions:

* Do static analysis and prefetch all included templates. This won't work if you want template name sto be dynamic.
* Return a placeholder and replace it after included templates rendered successfully.

There's an [example project][bl] applying the latter solution. I think it'll be great to implement  `includeAsync`, `layoutAsync`, and a `.renderAsync()` method within shopify-liquid. What do you think?

[bl]: https://github.com/brick-js/brick-liquid
[sync]: https://github.com/harttle/shopify-liquid#async-support

**Comment by thardy** [comment]
I'm curious as to the aversion to async in nodejs, since everything in node is built around the concept of async.  What is the benefit of synchronous rendering?  I read your readme, and I'm not seeing the benefit.

**Comment by harttle** [comment]
I believe template engine is compute-intensive, parsing HTML string and rendering data into it. While layouts and includes requires I/O interactions (fs or db), these functions should be implemented within template systems rather than template engine.

For convenience, shopify-liquid implemented synchronous thus simple layout and include. Maybe we need a template system implementation :)

**Comment by thardy** [comment]
I will look into wrapping the engine with something async.  Hopefully, I will find some time tonight or tomorrow morning.  I imagine I'll just start with something simple in front of renderFile.

**Comment by thardy** [comment]
I took a quick look at it last night, but did not make much progress.  I looked at the Basic-Liquid project briefly, and there seemed to be some significant differences between the code.  If you have an idea for includeAsync, renderAsync, and layoutAsync, I'd love to see those.

**Comment by harttle** [comment]
Alright, I will implement a `registerTagAsync` this week, which will allow tags that return Promises work with shopify-liquid.

**Comment by thardy** [comment]
Have a look at this commit in my fork - https://github.com/thardy/shopify-liquid/commit/4626f8f6bfdf5c026a725518cd98e0af71ff8759.  I added a test for nested includes and got async working.  I added Bluebird because it's faster than the default Promise library and I'm already using it, but you'll probably want to go with the built in module.  I'm sure my solution isn't the most modular, but maybe it can give you some ideas to speed your development.  Notice the use of the htmlBlocks array and use of the index in the renderTemplates function.  If you track each block by the index that they come in on synchronously, there's no need to use placeholders.

**Comment by thardy** [comment]
Also, the native-or-bluebird package is good flexible Promise package for low level packages to use.  If the consumer is using Bluebird, you can use that too and take advantage of the performance boost of Bluebird.  If the consumer does not have Bluebird, then everything still works.

**Comment by harttle** [comment]
Great implementation! Override `getTemplate` method is ok, but could it be better to make it a config parameter? If you're are ready, feel free to post a pull request. I can help you to pass all other tests.

**Comment by thardy** [comment]
I haven't had a chance to work on it this week, but I will put together a pull request soon.  Going out of town this weekend, so it might be early next week.

**Comment by thardy** [comment]
I've submitted a pull request with my changes.  Let me know if you want help pressing forward with the conversion to Promises.  My changes only have the include tag working, and I've only ran one test on that.  My next step was going to be getting all the other tests passing, but I'd rather not work on the same things you're going to work on.  I also want to get your feedback on the implementation and see if you want anything fundamental changed before I go about making a lot of sweeping changes.

**Comment by harttle** [comment]
There seems no big problem, while promises will make tag implementation trivial, which is inevitable. I don't have much time recently, please go on.

**Comment by thardy** [comment]
Sounds good.  Hopefully, I can get started on the other tests tomorrow.

**Comment by thardy** [comment]
I made some good progress on this last weekend.  I hope to finish it this weekend.

**Comment by thardy** [comment]
I've created a pull request that has all tests passing except the express tests in tests/liquid.js.  I commented those out.  I basically just ran out of steam :), but they should be easy to do.
