### ISSUE TITLE
{{ someVar | default: "this" }}

### ISSUE THREAD

**Issue by iggyZiggy** [harttle/shopify-liquid#30]
this doesn't work, tried with:
true/false
empty string
null
undefined

results is always empty string

**Comment by harttle** [comment]
@1.7.9, shopify-liquid applies `isTruthy` in the `default` filter. As proposed in #26, `isTruthy` implementation is compatible with [The Ruby Version][ruby].

[ruby]: https://shopify.github.io/liquid/basics/truthy-and-falsy/

**Comment by iggyZiggy** [comment]
tried that too, according to ruby version empty string is truthy but in js that's false, so using !!someEmptyStr returns false, and even when set manually to false I still don't get the default value but an empty string

**Comment by harttle** [comment]
The latest version should resolve this issue, see this jsfiddle: <https://jsfiddle.net/su3h56ts/>

**Comment by iggyZiggy** [comment]
Updated to the latest version but still doesn't work, here's the code, variables and logs, maybe it will help

part of the code
```
    console.log(mailSchedule.html, business.firstName);
    if(!business.firstName)business.firstName=false;
    console.log("firstName:", business.firstName);
    liquid.parseAndRender(mailSchedule.html, business).then(function(liquified){
      console.log("liquified:", liquified);
      mailSchedule.html = liquified;
      finish();
    })
```

part of the object holding the html variable
```
html: '<p>hey {{ firstName | default:&#34;test&#34; }}<br/></p>'
```

output in logs:
```
<p>hey {{ firstName | default:&#34;test&#34; }}<br/></p>
firstName: false
liquified: <p>hey <br/></p>
```

**Comment by harttle** [comment]
Since `{{ }}` enforces liquid syntax, the `"` should not be HTML escaped. The following template string should work as you expected.

```liquid
mailSchedule.html = '<p>hey {{ firstName | default:"test" }}<br/></p>'
```
`{{ firstName | default:&#34;test&#34; }}` will trigger a `ParseError` in Liquid. This exception will be cached and empty string will be generated by default. To catch filter exceptions, set the [`strict_filters`][opts] option.

[opts]: https://github.com/harttle/shopify-liquid#options

**Comment by iggyZiggy** [comment]
I've seen [here](https://github.com/harttle/shopify-liquid/blob/master/filters.js) that unescape and escape functions exists, figured it's already applied to whole string. Can that function/filter be called just on that part or do i need to make some kind of pre-parser/workaround before feeding liquid with it?
It would make my life a lot easier if i wouldn't need to parse content inside of {{ }} considering liquid already has a way to do it.

**Comment by harttle** [comment]
> Can that function/filter be called just on that part 

No. Filter functionalities only apply to values of context variables, not the filter syntax itself.

Unescape HTML is quite easy, but `{{ firstName | default:&#34;test&#34; }}` is just not valid in Liquid syntax.
