### ISSUE TITLE
Rendering includes with their own models

### ISSUE THREAD

**Issue by thardy** [harttle/shopify-liquid#4]
I have another requirement that I'm not sure how to implement using shopify-liquid.  My cms uses the concept of template objects.  It's basically a javascript object that has a template property that is the liquid template, and every other property is the model.  I realize I'll probably need to fork and make some changes to get this to happen, but I wanted to run it by you first to get your feedback.  For starters, I don't know how to pass an object as the model into an include.  I'd like to be able to:

- include my template objects in other templates
- have the included template objects use their own models in rendering themselves
- allow the parent to override any model properties that share the same name
- chain the above all the way to the top of a nested include chain (allow parents to override any model properties in their nested includes if they have the same name)

Here's an example:
```
var templateObjectOne = { 
    name: "TemplateHeader", 
    title: "Fancy Title", 
    favoriteNumber: 11, 
    template: "<header>{{title}}-{{favoriteNumber}}</header>"
};
// Need to somehow default the "include 'TemplateHeader'" to use the model in templateObjectOne.
//  Perhaps just completely alter includes to expect templateObjects in my fork
var templateObjectTwo = { 
    name: "TemplateWithInclude", 
    favoriteNumber: 7,
    template: "{% include 'TemplateHeader' %}<div>some content</div>"
};
// Ideally, I would change to simply - engine.render(templateObjectTwo);
var tpl = engine.parse(templateObjectTwo.template); 
var output = engine.render(tpl, templateObjectTwo); 
// should equal "<header>Fancy Title-7</header><div>some content</div>"
```
I'd love to get your thoughts on this, especially on any quick wins or preferred extension points with what you have already.  I'd prefer to make as few changes as possible to your code.

Thanks,
Tim

**Comment by harttle** [comment]
I believe it'll be a quick solution to override the `include` tag by simply calling [registerTag][registerTag]. 

Note that shopify-liquid renders in synchronous fashion, so you may need to apply some patches to allow async template resolving. This can be done by returning a placeholder (maybe a HASH), and replacing it after included template resolved and rendered.

[registerTag]: https://github.com/harttle/shopify-liquid#register-tags
