### ISSUE TITLE
Include variables.

### ISSUE THREAD

**Issue by randohinn** [harttle/shopify-liquid#8]
Ahh, found a missing feature. Would be super nice, if we could have the ability to define or pass variables for include statements. Such as 

```
  {% assign sys = system %}
  {% include 'views/components/admin-toolbar' %}
```

or 

`  {% include 'views/components/admin-toolbar', sys = system %}`. These methods currently give `Error: tag sys not found
`. Having these would be super useful, as this works in the official liquid markup.

**Comment by harttle** [comment]
Both of these methods should work, see https://github.com/harttle/shopify-liquid/blob/master/test/tags.js#L52 for the first method.

For the second one, see: https://github.com/harttle/shopify-liquid/blob/master/test/tags.js#L52

If you still have problem, please post the whole template file.

**Comment by randohinn** [comment]
I was being stupid... Apparently I've forgotten how to use liquid...

**Comment by harttle** [comment]
Sorry...
