### ISSUE TITLE
strict* settings

### ISSUE THREAD

**Issue by ScottFreeCode** [harttle/shopify-liquid#9]
Are there any plans to implement [`strict_variables` and/or `strict_filters`](https://github.com/shopify/liquid#undefined-variables-and-filters) (or `strictVariables`/`strictFilters` to fit JS style)? This would be particlarly useful in an Express environment as it would allow the application author to choose whether to show the end user an incorrectly rendered page or a 500 error (depending on how the templating can affect the app functionality, one or the other may be preferable in different apps).

**Comment by harttle** [comment]
Sounds good. It will be supported soon.

**Comment by ScottFreeCode** [comment]
Wow, that was fast! 👍 Thanks!

Out of curiousity, is it available in the `express` engine shortcut? That would be perfect.

**Comment by harttle** [comment]
Not by now. What syntax do you suggest?

**Comment by ScottFreeCode** [comment]
Hmm... Well, I would figure that either these two variables can be added to the `options` passed to the factory (alongside `root` and `extname`) to set the defaults for the various `render`-like calls, or the same options argument as in the `render`-like calls could be added to `express`, e.g. `express({ strict_variables: true })`, which would then be used in the `renderFile` call in the returned Express engine function. The latter is obviously much simpler to implement, though the former provides more flexibility (set options once, they apply anywhere that instance of Liquid is used).

**Comment by ScottFreeCode** [comment]
(Editted to clarify `express` -> `engine.express`)
